# Default values for qms-system
replicaCount: 1

image:
  repository: ghcr.io/jinkaiteo/qms
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: qms-local.company.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

# Environment specific configuration
environment: development

# Database configuration
database:
  host: postgres-service
  port: 5432
  name: qms_db
  user: qms_user

# Redis configuration  
redis:
  host: redis-service
  port: 6379

# Application configuration
app:
  secretKey: "change-in-production"
  debug: true
  logLevel: "INFO"